services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_DATABASE=hydrosat_db
      - ADMIN_NAME=hydrosat
      - ADMIN_PASSWORD=hydrosat
      - USER_PASSWORD=password
      - JWT_SECRET=hydrosat
      - GOOGLE_APPLICATION_CREDENTIALS=/service-accounts/nlp.json
    volumes:
      - .:/app
      - /app/node_modules
      - ~/Documents/service-accounts:/service-accounts
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hydrosat_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
